### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/label'

### ISSUE THREAD

**Issue by imsanjoykb** [altaga/DBSE-monitor#5]
When I run the Emotion Detection notebook.py file its through Permission Error

Error:
```
(base) ecl@ecl-desktop:~/DBSE-monitor/Emotiondetection$ python3 notebook.py
Traceback (most recent call last):
  File "notebook.py", line 128, in <module>
    with open(current_dir+'/label', "wb") as f:
PermissionError: [Errno 13] Permission denied: '/label'
```

At first I try to solve this using
`chmod -R 777 /home/ecl/DBSE-monitor/Jetson/Emotiondetection`

Then 
`chmod -R 777 /home/ecl/DBSE-monitor/Jetson/Emotiondetection/label`

But still get error. Are there any suggestion to solve this error.....

**Comment by altaga** [comment]
I made a change to read the directory correctly, for some reason it worked on the jetson nano when the project was created, however the error has already been corrected.

![image](https://user-images.githubusercontent.com/16561990/140799694-ab3cca85-1d89-4314-8c83-82ed8979e3be.png)

pd. If you have any error with OpenCV,  install through pypi

    pip install opencv-python

**Comment by altaga** [comment]
> When I run the Emotion Detection notebook.py file its through Permission Error
> 
> Error:
> 
> ```
> (base) ecl@ecl-desktop:~/DBSE-monitor/Emotiondetection$ python3 notebook.py
> Traceback (most recent call last):
>   File "notebook.py", line 128, in <module>
>     with open(current_dir+'/label', "wb") as f:
> PermissionError: [Errno 13] Permission denied: '/label'
> ```
> 
> At first I try to solve this using `chmod -R 777 /home/ecl/DBSE-monitor/Jetson/Emotiondetection`
> 
> Then `chmod -R 777 /home/ecl/DBSE-monitor/Jetson/Emotiondetection/label`
> 
> But still get error. Are there any suggestion to solve this error.....

I made a change to read the directory correctly, for some reason it worked on the jetson nano when the project was created, however the error has already been corrected.

![image](https://user-images.githubusercontent.com/16561990/140799694-ab3cca85-1d89-4314-8c83-82ed8979e3be.png)

pd. If you have any error with OpenCV,  install through pypi

    pip install opencv-python
